#!/bin/bash

# RemnaGuard Interactive Installer
# Usage: ./install.sh [NODE_NAME] [master|worker]

set -e

INSTALL_DIR="/opt/remnaguard"

echo "========================================"
echo "   🛡️  RemnaGuard Installer Setup"
echo "========================================"

# --- FUNCTIONS ---

# Deploy Function
deploy() {
    echo ">>> Building and Starting..."
    docker compose up -d --build
    
    echo "========================================"
    echo "✅ Deployment Complete!"
    echo "   Node: ${NODE_NAME:-Monitor}"
    echo "   Status: Online 🟢"
    echo "========================================"
}

# Helper to read input with default
# Usage: read_input "Prompt" "Default" "VAR_NAME" [is_sensitive]
read_input() {
    local prompt="$1"
    local default="$2"
    local var_name="$3"
    local is_sensitive="$4"
    local input=""
    
    local display_default="$default"
    # Mask if sensitive and default exists
    if [ "$is_sensitive" == "true" ] && [ -n "$default" ]; then
        display_default="********"
    fi
    
    if [ -n "$default" ]; then
        read -p "$prompt [$display_default]: " input
        export $var_name="${input:-$default}"
    else
        while [ -z "$input" ]; do
            read -p "$prompt: " input
        done
        export $var_name="$input"
    fi
}

# --- MAIN LOGIC ---

# 1. Node Name
if [ -z "$1" ]; then
    read_input "Enter Monitor Name" "RemnaGuard-Monitor" "NODE_NAME"
else
    NODE_NAME="$1"
fi

echo ">>> Configuring $NODE_NAME as Central Monitor..."

# 2. Install Docker if missing
if ! command -v docker &> /dev/null; then
    if [[ "$(uname -s)" == "Darwin" ]]; then
        echo "⚠️  Docker is not installed."
        echo "❌ On macOS, please install Docker Desktop manually: https://www.docker.com/products/docker-desktop"
        exit 1
    else
        echo "Docker not found. Installing..."
        curl -fsSL https://get.docker.com | sh
    fi
fi

# 3. Setup Directory
echo ">>> Setting up installation directory at $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"

# explicit copy to avoid copying venv, .git, or other garbage
echo ">>> Copying project files..."
cp -r src "$INSTALL_DIR/"
cp Dockerfile docker-compose.yml requirements.txt "$INSTALL_DIR/"

# Copy .env if exists locally to preserve config during migration
if [ -f .env ]; then
    cp .env "$INSTALL_DIR/"
fi

# Copy self (install.sh)
cp install.sh "$INSTALL_DIR/"

cd "$INSTALL_DIR"

# 4. Interactive Configuration
echo "----------------------------------------"
echo "🔑 Configuration (Press Enter for default)"
echo "----------------------------------------"

# Load existing env if present
if [ -f .env ]; then
    echo "✅ Found existing configuration (.env)."
    read -p "Skip configuration and rebuild? [Y/n]: " SKIP_CONFIG
    SKIP_CONFIG=${SKIP_CONFIG:-Y}
    
    if [[ "$SKIP_CONFIG" =~ ^[Yy]$ ]]; then
        echo ">>> Skipping core configuration..."
        source .env
        
        # Check if Gemini Key is missing in existing env (for upgrade path)
        if [ -z "$GEMINI_API_KEY" ]; then
             echo "----------------------------------------"
             echo "🤖 AI Integration (Gemini)"
             echo "----------------------------------------"
             echo "To enable Smart Baselines and Anti-False-Positive verification,"
             echo "you need a Google Gemini API Key."
             read_input "Gemini API Key (Leave blank to disableAI)" "" "GEMINI_API_KEY" "true"
             
             if [ -n "$GEMINI_API_KEY" ]; then
                 echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> .env
                 echo ">>> Added Gemini Key to existing configuration."
             fi
        fi
        
        # Jump to Deploy immediately
        deploy
        exit 0
    fi
    source .env
fi

# Run Config if not skipped
read_input "Remnawave URL" "${REMNAWAVE_URL:-http://<PANEL_IP>:3000}" "INPUT_URL"
read_input "Remnawave API Token" "${REMNAWAVE_TOKEN}" "INPUT_TOKEN" "true"
read_input "Telegram Bot Token" "${TELEGRAM_BOT_TOKEN}" "INPUT_BOT_TOKEN" "true"
read_input "Admin IDs (comma separated)" "${ADMIN_IDS}" "INPUT_ADMINS"

echo "----------------------------------------"
echo "🤖 AI Integration (Gemini)"
echo "----------------------------------------"
read_input "Gemini API Key (Leave blank to disable AI)" "${GEMINI_API_KEY}" "INPUT_GEMINI_KEY" "true"

echo ">>> Generating .env file..."

# Generating .env
cat > .env <<EOF
# Generated by install.sh
NODE_NAME=$NODE_NAME
MONITOR_MODE=api-central

# Connectivity
REMNAWAVE_URL=$INPUT_URL
REMNAWAVE_TOKEN=$INPUT_TOKEN
TELEGRAM_BOT_TOKEN=$INPUT_BOT_TOKEN
ADMIN_IDS=$INPUT_ADMINS
GEMINI_API_KEY=$INPUT_GEMINI_KEY

# Config
LOG_LEVEL=INFO
HEARTBEAT_INTERVAL=21600 # 6 hours

# Detection Tunables
THROTTLE_MIN_USERS=3       # Trigger if > 3 users
THROTTLE_SPEED_LIMIT=50    # Trigger if < 50 KB/s (Total)
THROTTLE_PER_USER=10       # Trigger if < 10 KB/s (Per User)
EOF

echo ">>> .env created successfully."

# 5. Deploy
deploy
